<?php

namespace Gitek\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogPickplaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogPickplaceRepository extends EntityRepository
{
}
