<?php

namespace Gitek\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    public function findByOf( $of )
    {
        $em = $this->getEntityManager();

        $dql = "SELECT l
                    FROM FrontendBundle:Log l
                    WHERE l.of = :of";

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('of', $of);
//        print_r($consulta->getSQL());
        return $consulta->getResult();
    }

    public function findByOfOperacionComponente( $of, $operacion, $componente )
    {
        $em = $this->getEntityManager();

        $dql = "SELECT l
                    FROM FrontendBundle:Log l
                      JOIN l.detalles d
                    WHERE l.of = :of
                      AND l.operacion = :operacion
                      AND d.componente = :componente";

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('of', $of);
        $consulta->setParameter('operacion', $operacion);
        $consulta->setParameter('componente', $componente);
//        print_r($consulta->getSQL());
        return $consulta->getResult();
    }

    public function findPorOperacion( $operacion  )
    {
        $em = $this->getEntityManager();

        $dql = "SELECT l
                    FROM FrontendBundle:Log l

                    WHERE l.operacion = :operacion";

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('operacion', $operacion);
        return $consulta->getResult();
//        return $consulta->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
    }

    public function findPorOfOperacion($of, $operacion) {
        $em = $this->getEntityManager();

        $dql = "SELECT l
                    FROM FrontendBundle:Log l
                    WHERE l.of = :of
                    AND l.operacion = :operacion";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('operacion', $operacion);
        $consulta->setParameter('of', $of);
        return $consulta->getResult();

    }

}
