<?php

namespace Gitek\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogSerigrafiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogSerigrafiaRepository extends EntityRepository
{
}
