<?php

namespace Gitek\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function findUsuariopornombre($nombre)
    {
        $em = $this->getEntityManager();

        $dql = "SELECT u
                    FROM BackendBundle:Usuario u
                    WHERE u.nombre LIKE :usuario";

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('usuario', $nombre);
//        print_r($consulta->getSQL());
        return $consulta->getResult();
    }
}
