<?php

namespace Gitek\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValidacionSerigrafiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidacionSerigrafiaRepository extends EntityRepository
{
    public function findSerigrafiaVisible()
    {
        $em = $this->getEntityManager();

        $dql = "SELECT v
                    FROM BackendBundle:ValidacionSerigrafia v
                    WHERE v.mostrar = :mostrar";

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('mostrar', 1);
//        print_r($consulta->getSQL());
        return $consulta->getResult();
    }
}
