<?php

namespace Gitek\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValidacionPickPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidacionPickPlaceRepository extends EntityRepository
{
}
