security:
    encoders:
        Gitek\BackendBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
 
    providers:
        user_db:
            entity: { class: Gitek\BackendBundle\Entity\Usuario, property: nombre }
 
    firewalls:
        main:
            pattern:    ^/
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: xlknco82yephljw-l9yikenl-n3@34knlkb3lºb
                lifetime: 28800 # 8 Horas
                path: /.*
                domain: ~
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /dashboard, roles: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }