frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:login }

login:
    path: /login
    defaults: { _controller: FrontendBundle:Default:login}

login_check:
    path: /logincheck
    defaults: { _controller: FrontendBundle:Default:logincheck}
    requirements: { _method: post }

logout:
    path: /logout
    defaults: { _controller: FrontendBundle:Default:logout}

dashboard:
    path: /dashboard/
    defaults: { _controller: FrontendBundle:Default:dashboard}

fase2:
    path: /fase2
    defaults: { _controller: FrontendBundle:Default:fase2}