frontend_admin_logdetail:
    resource: "@FrontendBundle/Resources/config/routing/logdetail.yml"
    prefix:   /admin/logdetail

frontend_admin_log:
    resource: "@FrontendBundle/Resources/config/routing/log.yml"
    prefix:   /admin/log

frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:login }

login:
    path: /login
    defaults: { _controller: FrontendBundle:Default:login}

login_check:
    path: /logincheck
    defaults: { _controller: FrontendBundle:Default:logincheck}
    requirements: { _method: post }

logout:
    path: /logout
    defaults: { _controller: FrontendBundle:Default:logout}

dashboard:
    path: /dashboard/
    defaults: { _controller: FrontendBundle:Default:dashboard}

fase2:
    path: /fase2
    defaults: { _controller: FrontendBundle:Default:fase2}

find_of_post:
    path: /OrdenFabricacion
    defaults: { _controller: FrontendBundle:Default:findof}
    requirements: { _method: post }

find_of:
    path: /OrdenFabricacion/{of}
    defaults: { _controller: FrontendBundle:Default:findof , of: '' }

find_of_operacion:
    path: /OrdenFabricacionOperacion
    defaults: { _controller: FrontendBundle:Default:findoperacion }
    requirements: { _method: post }
    options:
            expose: true

validacion1:
    path: /validacion1/{operacion}
    defaults: { _controller: FrontendBundle:Default:validacion1 }
    requirements: { _method: get }

validacion1post:
    path: /validacion1
    defaults: { _controller: FrontendBundle:Default:validacion1 }
    requirements: { _method: post }

addComponente:
    path: /addComponente
    defaults: { _controller: FrontendBundle:Default:addComponente }
    requirements: { _method: post }
    options:
            expose: true

removeComponente:
    path: /removeComponente
    defaults: { _controller: FrontendBundle:Default:removeComponent }
    requirements: { _method: post }
    options:
            expose: true

validacion2:
    path: /validacion2/{operacion}
    defaults: {_controller: FrontendBundle:Default:Validacion2 }
    requirements: { method: get}
    options:
            expose: true

dovalidacion2:
    path: /dovalidacion2/{operacion}
    defaults: {_controller: FrontendBundle:Default:Dovalidacion2}
    requirements: { method: get}
    options:
            expose: true

validacion3:
    path: /validacion3/{operacion}
    defaults: {_controller: FrontendBundle:Default:Validacion3 }
    requirements: { method: get}
    options:
            expose: true

dovalidacion3:
    path: /dovalidacion3/{operacion}
    defaults: {_controller: FrontendBundle:Default:Dovalidacion3}
    requirements: { method: get}
    options:
            expose: true

validacion4:
    path: /validacion4/{operacion}
    defaults: {_controller: FrontendBundle:Default:Validacion4 }
    requirements: { method: get}
    options:
            expose: true

dovalidacion4:
    path: /dovalidacion4/{operacion}
    defaults: {_controller: FrontendBundle:Default:Dovalidacion4}
    requirements: { method: get}
    options:
            expose: true

validacion5:
    path: /validacion5/{operacion}
    defaults: {_controller: FrontendBundle:Default:Validacion5 }
    requirements: { method: get}
    options:
            expose: true

dovalidacion5:
    path: /dovalidacion5/{operacion}
    defaults: {_controller: FrontendBundle:Default:Dovalidacion5}
    requirements: { method: get}
    options:
            expose: true

validacion6:
    path: /validacion6/{operacion}
    defaults: {_controller: FrontendBundle:Default:Validacion6 }
    requirements: { method: get}
    options:
            expose: true

cambiobobina:
    path: /cambio
    defaults: { _controller: FrontendBundle:Default:Cabiarbobina }

cambio_bobina_lee_of:
    path: /cambio/leeof
    defaults: { _controller: FrontendBundle:Default:cambioBobinaLeeOf}

cambio_bobina_lee_operacion:
    path: /cambio/leeoperacion
    defaults: { _controller: FrontendBundle:Default:cambioBobinaLeeOperacion}

cambio_bobina_lee_salida:
    path: /cambio/sale
    defaults: { _controller: FrontendBundle:Default:cambioBobinaSale}

cambio_bobina_lee_entra:
    path: /cambio/entra
    defaults: { _controller: FrontendBundle:Default:cambioBobinaEntra}