# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Gitek\BackendBundle\Admin\AuxsiplaceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Auxiliares", label: "Auxiliar Siplace" }
        arguments:
            - ~
            - Gitek\BackendBundle\Entity\AuxSiplace
            - ~
        calls:
            - [ setTranslationDomain, [BackendBundle]]