backend_admin_usuarios:
    resource: "@BackendBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuarios

BackendBundle_admin:
        resource: "@BackendBundle/Resources/config/routing/menus.yml"
        prefix:   /menus

BackendBundle_admin_auxdiodos:
        resource: "@BackendBundle/Resources/config/routing/auxdiodos.yml"
        prefix:   /auxdiodos

BackendBundle_admin_auxsiplace:
        resource: "@BackendBundle/Resources/config/routing/auxsiplace.yml"
        prefix:   /auxsiplace

BackendBundle_admin_auxserigrafia:
        resource: "@BackendBundle/Resources/config/routing/auxserigrafia.yml"
        prefix:   /auxserigrafia